# Generated by Django 5.0.6 on 2024-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
